// <auto-generated />
using System;
using ClienteNet6.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClienteNet6.Server.Migrations
{
    [DbContext(typeof(AppGerVeiculosContext))]
    [Migration("20220606164457_veiculosInfracoesInit")]
    partial class veiculosInfracoesInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");

            modelBuilder.Entity("ClienteNet6.Shared.EntityFramework.Infracao", b =>
                {
                    b.Property<string>("Ait")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("Emissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Renavam")
                        .HasColumnType("int(17)");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Ait");

                    b.HasIndex("Renavam");

                    b.ToTable("Infracao");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                });

            modelBuilder.Entity("ClienteNet6.Shared.EntityFramework.Veiculo", b =>
                {
                    b.Property<int>("Renavam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(17)");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("char(17)");

                    b.Property<string>("Cor")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.HasKey("Renavam");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.HasIndex("Placa");

                    b.ToTable("Veiculo");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                });

            modelBuilder.Entity("ClienteNet6.Shared.EntityFramework.Infracao", b =>
                {
                    b.HasOne("ClienteNet6.Shared.EntityFramework.Veiculo", "Veiculo")
                        .WithMany("Infracoes")
                        .HasForeignKey("Renavam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ClienteNet6.Shared.EntityFramework.Veiculo", b =>
                {
                    b.Navigation("Infracoes");
                });
#pragma warning restore 612, 618
        }
    }
}
